#pragma once

#include <string>
#include <ctime>
#include <cstdlib>

#include <Utils\common.h>

using namespace std;

namespace VOB
{
	namespace Auth {

		class DllExport User
		{

			/* helper string with alpha numeric characters for salt generation */
			static const string ALNUMS;

			/* length of salt */
			static const int SALT_LENGTH;

			/* login of user */
			string login;

			/* real name of user */
			string name;

			/* password */
			string password;

			/* salt */
			string salt;

			/*
			create salt and write it
			*/
			void createSalt();

		public:

			/*
			create uninitialised user
			*/
			User();

			/*
			create full defined user
			*/
			User(string login, string name);

			/*
			copytor
			*/
			User(const User &other);

			/*
			do nothing
			*/
			virtual ~User();

			/*
			return current login
			*/
			const string &GetLogin() const;

			/*
			return current name
			*/
			const string &GetName() const;

			/*
			set new name
			*/
			void SetName(const string &newName);

			/*
			return current password (generated by password policy)
			*/
			const string &GetPassword() const;

			/*
			set new password
			*/
			void SetPassword(const string &password);
			
			/*
			return salt
			 */
			const string &GetSalt() const;

			/*
			assign operator
			*/
			User &operator =(const User &other);

		};

	}
}